2023-11-05 13:39:33,407 INFO    MainThread:47760 [wandb_setup.py:_flush():76] Current SDK version is 0.15.2
2023-11-05 13:39:33,407 INFO    MainThread:47760 [wandb_setup.py:_flush():76] Configure stats pid to 47760
2023-11-05 13:39:33,407 INFO    MainThread:47760 [wandb_setup.py:_flush():76] Loading settings from /Users/josepsmachine/.config/wandb/settings
2023-11-05 13:39:33,408 INFO    MainThread:47760 [wandb_setup.py:_flush():76] Loading settings from /Users/josepsmachine/Documents/PROGRAMMING/BioBytes_Uib_Datathon2023/wandb/settings
2023-11-05 13:39:33,408 INFO    MainThread:47760 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-11-05 13:39:33,408 INFO    MainThread:47760 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-11-05 13:39:33,408 INFO    MainThread:47760 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-11-05 13:39:33,408 INFO    MainThread:47760 [wandb_init.py:_log_setup():507] Logging user logs to /Users/josepsmachine/Documents/PROGRAMMING/BioBytes_Uib_Datathon2023/wandb/run-20231105_133933-26pho1ks/logs/debug.log
2023-11-05 13:39:33,408 INFO    MainThread:47760 [wandb_init.py:_log_setup():508] Logging internal logs to /Users/josepsmachine/Documents/PROGRAMMING/BioBytes_Uib_Datathon2023/wandb/run-20231105_133933-26pho1ks/logs/debug-internal.log
2023-11-05 13:39:33,408 INFO    MainThread:47760 [wandb_init.py:init():547] calling init triggers
2023-11-05 13:39:33,408 INFO    MainThread:47760 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-11-05 13:39:33,408 INFO    MainThread:47760 [wandb_init.py:init():571] re-initializing run, found existing run on stack: wimtjzb1
2023-11-05 13:39:33,411 INFO    MainThread:47760 [wandb_run.py:_finish():1893] finishing run haradai/datahon_uib_2023/wimtjzb1
2023-11-05 13:39:33,411 INFO    MainThread:47760 [jupyter.py:save_history():445] not saving jupyter history
2023-11-05 13:39:33,411 INFO    MainThread:47760 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-11-05 13:39:33,411 INFO    MainThread:47760 [wandb_init.py:_jupyter_teardown():435] cleaning up jupyter logic
2023-11-05 13:39:33,412 INFO    MainThread:47760 [wandb_run.py:_atexit_cleanup():2127] got exitcode: 0
2023-11-05 13:39:33,412 INFO    MainThread:47760 [wandb_run.py:_restore():2110] restore
2023-11-05 13:39:33,412 INFO    MainThread:47760 [wandb_run.py:_restore():2116] restore done
2023-11-05 13:39:36,530 INFO    MainThread:47760 [wandb_init.py:init():596] starting backend
2023-11-05 13:39:36,530 INFO    MainThread:47760 [wandb_init.py:init():600] setting up manager
2023-11-05 13:39:36,532 INFO    MainThread:47760 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-11-05 13:39:36,533 INFO    MainThread:47760 [wandb_init.py:init():606] backend started and connected
2023-11-05 13:39:36,538 INFO    MainThread:47760 [wandb_run.py:_label_probe_notebook():1238] probe notebook
2023-11-05 13:39:36,539 INFO    MainThread:47760 [wandb_run.py:_label_probe_notebook():1248] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-11-05 13:39:36,539 INFO    MainThread:47760 [wandb_init.py:init():700] updated telemetry
2023-11-05 13:39:36,566 INFO    MainThread:47760 [wandb_init.py:init():737] communicating run to backend with 60.0 second timeout
2023-11-05 13:39:51,816 WARNING MainThread:47760 [wandb_init.py:init():1172] interrupted
Traceback (most recent call last):
  File "/Users/josepsmachine/miniforge3/envs/ML/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1150, in init
    run = wi.init()
  File "/Users/josepsmachine/miniforge3/envs/ML/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 740, in init
    result = run_init_handle.wait(
  File "/Users/josepsmachine/miniforge3/envs/ML/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/Users/josepsmachine/miniforge3/envs/ML/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/Users/josepsmachine/miniforge3/envs/ML/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/Users/josepsmachine/miniforge3/envs/ML/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/josepsmachine/miniforge3/envs/ML/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
